### ISSUE TITLE
"https://*.beyondco.de/" urls results in an error

### ISSUE THREAD

**Issue by moshekatz** [beyondcode/tailwind-jit-api#1]
Hey,
It might be something that I'm missing, but it seems like any url that matches **"https://*.beyondco.de/"** result in an error.

That includes the script tag that is being used in this project: [https://tailwind-jit.beyondco.de/tailwind.js](https://tailwind-jit.beyondco.de/tailwind.js)

But also others:
[https://banners.beyondco.de/](https://banners.beyondco.de/)

In any case, thanks in advance, truly inspiring software.

Screenshots:

![image](https://user-images.githubusercontent.com/25473107/116575538-65ab5000-a917-11eb-92b1-6f550ece8597.png)

![image](https://user-images.githubusercontent.com/25473107/116575584-722fa880-a917-11eb-8d68-e5e7ab27915e.png)

**Comment by sschlein** [comment]
We've switched our domain to Cloudflare an hour ago, so that could be the reason.

Any chance that this has something to do with your network? There are >25 people on the site at the moment and our sites also work for us.

**Comment by moshekatz** [comment]
It could be my network, it's just that other sites (e.g: github.com, beyondco.de without the subdomain) works for me.
Also flushed my dns resolver cache just to be sure that's not the issue.

In any case, will wait an hour and give an update if the problem is resolved.

**Comment by moshekatz** [comment]
Hey again, here with an update as promised - the urls still seems to be inaccessible.

**Comment by sschlein** [comment]
It should be fine now. We missed some CNAME records 🙈
